#+TITLE: Set up Gitlab Server
#+AUTHOR: VLEAD Systems
#+DATE: [2018-02-27 Tue]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


* Introduction
  This document is about the step-by-step process to install GitLab CE
  (Community Edition) on Ubuntu 16.04 server.

* Requirements
 - A server running Ubuntu-16.04 on your system.
 - A non-root user with sudo privileges setup on your server.
 - 2 core CPU to support up to 500 users.
 - 2 GB Memory to support up to 500 users.
 - A static IP address is configure on your system.

* Update the System
  Before starting with the Gitlab installation, you will need to
  update the system's package repository database with the latest
  version. You can do this with the following command:

  #+BEGIN_EXAMPLE
  $ sudo apt-get update && sudo apt-get upgrade
  #+END_EXAMPLE

  Once your package repository is up-to-date, you can proceed with
  installing required dependencies.

* Install Prerequisites
  Use the following commands to install required dependencies to begin
  Gitlab installation.
  
  #+BEGIN_EXAMPLE
  $ sudo apt-get install ca-certificates curl openssh-server postfix git
  #+END_EXAMPLE
  
  Once installation is completed, you can proceed to install GitLab.

* Install Gitlab Server
  Once all the required dependencies are installed, now you can
  install GitLab by downloading GitLab installation script.

  To download the installation script, run the following command:
  
  #+BEGIN_EXAMPLE
  $ curl -LO https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
  #+END_EXAMPLE
  
  Once download is completed, run the downloaded installation script with the following command:

  #+BEGIN_EXAMPLE
  $ sudo bash script.deb.sh
  #+END_EXAMPLE

  The above script will install and setup GitLab repository on your
  system. Once installation is complete, you can install the GitLab
  application by running the following command:

  #+BEGIN_EXAMPLE
  $ sudo apt-get install gitlab-ce
  #+END_EXAMPLE

  The above command will install all required components on your
  system.

* Configure Gitlab-CE Server
  Execute the following command to configure the Gitlab
  installation. This will make all the installations and required
  changes in order to run Gitlab community edition.

  #+BEGIN_EXAMPLE
  $ sudo gitlab-ctl reconfigure
  #+END_EXAMPLE

  Once configuration is complete, you can proceed to configure firewall.

* Configure UFW Firewall
  Before accessing the GitLab, you will need to allow SSH and HTTP
  service through UFW firewall. By default UFW is disabled on your
  system, so you need to enable it first. You can enable it with the
  following command:

  #+BEGIN_EXAMPLE
  $ sudo apt-get install -y ufw
  $ sudo ufw enable
  $ sudo ufw allow ssh
  $ sudo ufw allow http
  $ sudo ufw allow https
  #+END_EXAMPLE
  
  Now check the firewall status and make sure ssh, http, and https ports is on the list.

  #+BEGIN_EXAMPLE
  $ sudo ufw status
  #+END_EXAMPLE

  HTTP and HTTPS ports are configured.

* Configure Gitlab
  The configuration file is located at =/etc/gitlab/gitlab.rb= Some
  important settings to look at include =external_url=, where you can
  set your =ip= or your =domain name=.

  Open the =/etc/gitlab/gitlab.rb= file using an editor, such as vim,
  to start modifying the configuration:

  #+BEGIN_EXAMPLE
  $ sudo vim /etc/gitlab/gitlab.rb
  #+END_EXAMPLE

  Edit external_url around line =11=, find =external_url= and set the
  value to your =IP= or =domain adress=.

  #+BEGIN_EXAMPLE
  external_url 'http://your_IP_adress_OR_your_Domain'
  #+END_EXAMPLE

  After making the change, save =/etc/gitlab/gitlab.rb= file and close the editor.

  Run the below command to apply latest changes in =/etc/gitlab/gitlab.rb= file.

  #+BEGIN_EXAMPLE
  $ sudo gitlab-ctl reconfigure
  #+END_EXAMPLE

* Access Gitlab-CE Web UI
  Open your favourite web browser and type the URL
  [[http://your-server-ip]] or [[http://your-domain-name]].  You should see
  the following page in your web browser, where you will be asked to
  create a new password for root.

  Enter the new password twice and click on Change your password
  button.

  Next, you will need to sign in to web interface. You can sign in to
  administrative account by using the username =root= and your newly
  created password.
